"""nueva tabla productos

Revision ID: 16977063eac1
Revises: 7570ca280955
Create Date: 2024-07-26 22:47:17.571094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16977063eac1'
down_revision = '7570ca280955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
